language: r
sudo: false
cache: packages
warnings_are_errors: false

r:
  - oldrel
  - release
  - devel

r_packages:
  - covr

before_install:
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install -y libudunits2-dev libproj-dev libgeos++-dev libgdal-dev libv8-dev

after_success:
  - Rscript -e 'library(covr); codecov()'

r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual
